# Generated by Django 4.2 on 2023-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/profile/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/cv/'),
        ),
    ]
