# Generated by Django 4.2 on 2023-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userinfo_profile_pic_alter_userinfo_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
    ]
