# Generated by Django 4.2 on 2023-06-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_userinfo_phone_numner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone_numner',
            new_name='phone_number',
        ),
    ]
