# Generated by Django 4.2 on 2023-06-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_phone_numner_userinfo_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='account_type',
        ),
    ]
