# Generated by Django 4.2 on 2023-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_userinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
