# Generated by Django 4.2.1 on 2023-07-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_companyinfo_purchased_package'),
        ('pages', '0018_userinfo_purchased_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='purchased_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.pricingplan'),
        ),
    ]
