# Generated by Django 4.2.1 on 2023-07-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_userinfo_purchased_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='job_apply_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
