# Generated by Django 4.2.1 on 2023-06-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
