# Generated by Django 4.2.1 on 2023-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyinfo_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_days',
            field=models.TextField(blank=True, null=True),
        ),
    ]
