# Generated by Django 4.2.1 on 2023-06-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyinfo_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
