# Generated by Django 4.2.1 on 2023-06-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companygallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_image',
            field=models.FileField(blank=True, null=True, upload_to='static/job_images'),
        ),
    ]
