# Generated by Django 4.2.1 on 2023-06-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_req',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skillsandxperience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
