# Generated by Django 4.2.1 on 2023-06-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_job_industry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customizable_field1', models.CharField(blank=True, max_length=255)),
                ('customizable_field2', models.CharField(blank=True, max_length=255)),
                ('customizable_field3', models.CharField(blank=True, max_length=255)),
                ('customizable_field4', models.CharField(blank=True, max_length=255)),
                ('customizable_field5', models.CharField(blank=True, max_length=255)),
                ('customizable_field6', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
