# Generated by Django 4.2.1 on 2023-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_subscriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='invoice_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
