# Generated by Django 4.2.1 on 2023-07-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_subscriptionmodel_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='purchased_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.pricingplan'),
        ),
    ]
