# Generated by Django 4.2.1 on 2023-07-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_pricingplan_jobs_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='job_post_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
