# Generated by Django 4.2.1 on 2023-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='user_type',
            field=models.IntegerField(null=True),
        ),
    ]
